import type { Metadata } from "next";
import { Cormorant, Fustat } from "next/font/google";
import "./globals.css";

/**
 * Typography
 * ──────────────────────────────────────────────────────────────────────
 * Cormorant Regular  → all serif headings (H1–H5)
 * Fustat Light/Reg/Semibold → body, labels, H6
 *
 * The CSS variables below are remapped to Tailwind's `font-serif` and
 * `font-sans` in `app/globals.css` — so every `font-serif` / `font-sans`
 * class in the codebase renders in the KORA design system fonts without
 * any per-component edits.
 */

const cormorant = Cormorant({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  display: "swap",
  fallback: ["Georgia", "Times New Roman", "serif"],
});

const fustat = Fustat({
  variable: "--font-fustat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  display: "swap",
  fallback: ["system-ui", "-apple-system", "Segoe UI", "Roboto", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${cormorant.variable} ${fustat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
